"""users table

Revision ID: 446218673bf2
Revises: 829e904977e4
Create Date: 2018-09-15 22:30:52.528506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446218673bf2'
down_revision = '829e904977e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_about', table_name='user')
    op.drop_index('ix_user_birthdate', table_name='user')
    op.drop_index('ix_user_photo', table_name='user')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'photo')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.VARCHAR(length=200), nullable=True))
    op.add_column('user', sa.Column('photo', sa.BLOB(), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.DATE(), nullable=True))
    op.create_index('ix_user_photo', 'user', ['photo'], unique=1)
    op.create_index('ix_user_birthdate', 'user', ['birthdate'], unique=1)
    op.create_index('ix_user_about', 'user', ['about'], unique=1)
    # ### end Alembic commands ###
